#@ load("@ytt:data", "data")

apiVersion: kbld.k14s.io/v1alpha1
kind: Sources
sources:
- image: secretgen-controller
  path: .
  #@ if/end data.values.push_images:
  docker:
    build:
      #! Always rebuild image
      pull: true
      noCache: true

#@ if/end data.values.push_images:
---
apiVersion: kbld.k14s.io/v1alpha1
kind: ImageDestinations
destinations:
- image: secretgen-controller
  newImage: #@ data.values.image_repo
