#@data/values-schema
---
#@overlay/match missing_ok=True
#@overlay/match-child-defaults
#@schema/desc "Configuration explicity for developing secretgen-controller"
dev:
  #@schema/desc "Location of secretgen-controller image"
  image_repo: docker.io/ysethiya/carvel-secretgen-controller
  #@schema/desc "Development version"
  version: develop
  #@schema/desc "Comma separated list of supported architectures"
  platform: "linux/amd64,linux/arm64"
